/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_sunqi13_myapplication_TimeUtils */

#ifndef _Included_demo_sunqi13_myapplication_TimeUtils
#define _Included_demo_sunqi13_myapplication_TimeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_sunqi13_myapplication_TimeUtils
 * Method:    getNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_demo_sunqi13_myapplication_TimeUtils_getNum
        (JNIEnv *, jobject clazz, jint art);

#ifdef __cplusplus
}
#endif
#endif
